/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TubesPBO;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class AktivasiKartu extends javax.swing.JFrame {

    /**
     * Creates new form AktivasiKartu
     */
    public AktivasiKartu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id_kartu = new javax.swing.JTextField();
        pass_id = new javax.swing.JPasswordField();
        pass_ver = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(428, 504));
        getContentPane().setLayout(null);

        id_kartu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        id_kartu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_kartuActionPerformed(evt);
            }
        });
        getContentPane().add(id_kartu);
        id_kartu.setBounds(30, 220, 370, 40);

        pass_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pass_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_idActionPerformed(evt);
            }
        });
        getContentPane().add(pass_id);
        pass_id.setBounds(30, 290, 370, 40);

        pass_ver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pass_ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_verActionPerformed(evt);
            }
        });
        getContentPane().add(pass_ver);
        pass_ver.setBounds(30, 360, 370, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 153, 0));
        jButton1.setText("AKTIFKAN KARTU");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 420, 150, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 153, 0));
        jButton2.setText("BATAL");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(260, 420, 80, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TubesPBO/image/Ga-PayAktivasi.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 430, 510);

        setSize(new java.awt.Dimension(428, 504));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void id_kartuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_kartuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_kartuActionPerformed

    private void pass_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_idActionPerformed

    private void pass_verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_verActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_verActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try{
            
           if(pass_ver.getText().equals(pass_id.getText())){
               Connection koneksi = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/gapaytera","root","");
                Statement stat = koneksi.createStatement();
                String sql = "INSERT INTO aktivasikartu VALUES('"+id_kartu.getText()+"','"+pass_id.getText()+"',"+"0)";
            
                stat.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "AKTIVASI BERHASIL", "Aktivasi Kartu Ga-PayTera", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                new Menu().setVisible(true);
            }else{
               JOptionPane.showMessageDialog(null, "MASUKKAN KEMBALI PASSWORD DENGAN BENAR", "Aktivasi Kartu Ga-PayTera", JOptionPane.INFORMATION_MESSAGE);
               pass_id.setText("");
               pass_id.requestFocus();
               pass_ver.setText("");
               pass_ver.requestFocus(); //yang ini harus ada fatin biar dia kursornya langsung kekolomnya jadi karena salah dia yang dikosongin diverfikasinya aja
                }              
       }catch(SQLException ex){
           JOptionPane.showMessageDialog(null, "Koneksi Gagal!", "Informasi", JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        new Menu().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AktivasiKartu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AktivasiKartu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AktivasiKartu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AktivasiKartu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AktivasiKartu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField id_kartu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField pass_id;
    private javax.swing.JPasswordField pass_ver;
    // End of variables declaration//GEN-END:variables
}
